# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import zip_pb2 as zip__pb2


class ZipSearchingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ZipSearching = channel.unary_unary(
                '/ZipSearching/ZipSearching',
                request_serializer=zip__pb2.ZipInput.SerializeToString,
                response_deserializer=zip__pb2.ZipOutput.FromString,
                )


class ZipSearchingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ZipSearching(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ZipSearchingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ZipSearching': grpc.unary_unary_rpc_method_handler(
                    servicer.ZipSearching,
                    request_deserializer=zip__pb2.ZipInput.FromString,
                    response_serializer=zip__pb2.ZipOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ZipSearching', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ZipSearching(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ZipSearching(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ZipSearching/ZipSearching',
            zip__pb2.ZipInput.SerializeToString,
            zip__pb2.ZipOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
