# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zip.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tzip.proto\"+\n\x08ZipInput\x12\x0f\n\x07zipCode\x18\x01 \x01(\t\x12\x0e\n\x06radius\x18\x02 \x01(\x05\"\x1b\n\tZipOutput\x12\x0e\n\x06output\x18\x01 \x01(\t27\n\x0cZipSearching\x12\'\n\x0cZipSearching\x12\t.ZipInput\x1a\n.ZipOutput\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zip_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ZIPINPUT._serialized_start=13
  _ZIPINPUT._serialized_end=56
  _ZIPOUTPUT._serialized_start=58
  _ZIPOUTPUT._serialized_end=85
  _ZIPSEARCHING._serialized_start=87
  _ZIPSEARCHING._serialized_end=142
# @@protoc_insertion_point(module_scope)
